import tribalNationsData from '#data/tribalNations.csv';

export const tribalNations = tribalNationsData.sort((a, b) => (a.name > b.name ? 1 : -1));

export const states = [
  { name: 'Alabama', slug: 'alabama' },
  { name: 'Alaska', slug: 'alaska' },
  { name: 'Arizona', slug: 'arizona' },
  { name: 'Arkansas', slug: 'arkansas' },
  { name: 'California', slug: 'california' },
  { name: 'Colorado', slug: 'colorado' },
  { name: 'Connecticut', slug: 'connecticut' },
  { name: 'Delaware', slug: 'delaware' },
  { name: 'Florida', slug: 'florida' },
  { name: 'Georgia', slug: 'georgia' },
  { name: 'Idaho', slug: 'idaho' },
  { name: 'Illinois', slug: 'illinois' },
  { name: 'Indiana', slug: 'indiana' },
  { name: 'Iowa', slug: 'iowa' },
  { name: 'Kansas', slug: 'kansas' },
  { name: 'Kentucky', slug: 'kentucky' },
  { name: 'Louisiana', slug: 'louisiana' },
  { name: 'Maine', slug: 'maine' },
  { name: 'Maryland', slug: 'maryland' },
  { name: 'Massachusetts', slug: 'massachusetts' },
  { name: 'Michigan', slug: 'michigan' },
  { name: 'Minnesota', slug: 'minnesota' },
  { name: 'Mississippi', slug: 'mississippi' },
  { name: 'Missouri', slug: 'missouri' },
  { name: 'Montana', slug: 'montana' },
  { name: 'Nebraska', slug: 'nebraska' },
  { name: 'Nevada', slug: 'nevada' },
  { name: 'New Hampshire', slug: 'new-hampshire' },
  { name: 'New Jersey', slug: 'new-jersey' },
  { name: 'New Mexico', slug: 'new-mexico' },
  { name: 'New York', slug: 'new-york' },
  { name: 'North Carolina', slug: 'north-carolina' },
  { name: 'North Dakota', slug: 'north-dakota' },
  { name: 'Ohio', slug: 'ohio' },
  { name: 'Oklahoma', slug: 'oklahoma' },
  { name: 'Oregon', slug: 'oregon' },
  { name: 'Pennsylvania', slug: 'pennsylvania' },
  { name: 'Rhode Island', slug: 'rhode-island' },
  { name: 'South Carolina', slug: 'south-carolina' },
  { name: 'South Dakota', slug: 'south-dakota' },
  { name: 'Tennessee', slug: 'tennessee' },
  { name: 'Texas', slug: 'texas' },
  { name: 'Utah', slug: 'utah' },
  { name: 'Vermont', slug: 'vermont' },
  { name: 'Virginia', slug: 'virginia' },
  { name: 'Washington (State)', slug: 'washington' },
  { name: 'West Virginia', slug: 'west-virginia' },
  { name: 'Wisconsin', slug: 'wisconsin' },
  { name: 'Wyoming', slug: 'wyoming' },
];

export const topics = [
  { name: 'Agriculture', slug: 'agriculture' },
  { name: 'Animals', slug: 'animals' },
  { name: 'Artistry and Artifacts', slug: 'artistry-and-artifacts' },
  { name: 'Buildings', slug: 'buildings' },
  { name: 'Bureau Personnel', slug: 'bureau-personnel' },
  { name: 'Camps', slug: 'camps' },
  { name: 'Children', slug: 'children' },
  { name: 'Dances', slug: 'dances' },
  { name: 'Dress', slug: 'dress' },
  { name: 'Dwellings', slug: 'dwellings' },
  { name: 'Farming', slug: 'farming' },
  { name: 'Fishing', slug: 'fishing' },
  { name: 'Food Preparation', slug: 'food-preparation' },
  { name: 'Games and Recreation', slug: 'games-and-recreation' },
  { name: 'Groups', slug: 'groups' },
  { name: 'Hunting', slug: 'hunting' },
  { name: 'Landscapes', slug: 'landscapes' },
  { name: 'Leaders', slug: 'leaders' },
  { name: 'Military Service', slug: 'military-service' },
  { name: 'Portraits', slug: 'portraits' },
  { name: 'Reservations', slug: 'reservations' },
  { name: 'Schools', slug: 'schools' },
  { name: 'Transportation', slug: 'transportation' },
  { name: 'Tribal Councils', slug: 'tribal-councils' },
  { name: 'Villages', slug: 'villages' },
];
